name: ✨ Feature request
description: General idea for improving the project
labels: ["✨ Feature", "👀 Evaluation"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Ensure that our feature request form is appropriate for you.
      options:
        - label: This is a feature request
          required: true
        - label: This is not a **[duplicate](https://github.com/keefort/ASFItemCollector/issues?q=is%3Aissue)** of an existing issue
          required: true
        - label: My idea doesn't duplicate existing ASFItemCollector functionality
          required: true
        - label: My idea doesn't duplicate existing ASF functionality described on the **[wiki](https://github.com/JustArchiNET/ArchiSteamFarm/wiki)**
          required: true
  - type: textarea
    id: feature-purpose
    attributes:
      label: Feature purpose
      description: |
        Purpose of the feature - if it solves some problem, precise in particular which. If it benefits the program in some other way, precise in particular why.
        Present the underlying reason why this feature makes sense, and what is the context of it.
      placeholder: |
        As of today ASF offers variety of beverages, such as latte macchiato or cappuccino. I'd appreciate if ASF offered some no-milk options as well, for example espresso or ristretto.
        I believe it'd further improve the program offering the users wider selection, which is very convenient.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: |
        What would you like to see as a solution to the purpose specified by you above?
      placeholder: |
        Simply add an option to brew some no-milk types of coffee. The existing logic is fine, we just need wider choice!
    validations:
      required: true
  - type: textarea
    id: why-existing-not-sufficient
    attributes:
      label: Why currently available solutions are not sufficient?
      description: |
        Evaluate the existing solutions in regards to your requirements.
        If something you're suggesting is already possible, then explain to us why the currently available solutions are not sufficient.
        If it's not possible yet, then explain to us why it should be.
      placeholder: |
        I'm allergic to milk, there is currently no option to pick a beverage that doesn't include it.
        Temporarily I'm switching cup mid-brewing as a workaround, but that is suboptimal considering the milk wasted.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: |
        Everything else you consider worthy that we didn't ask for.
  - type: markdown
    attributes:
      value: |
        ---
        #### Thank you for taking the time to fill out this feature request.
